"use client"
import {useEffect,useRef,useState} from "react"
import {Camera,Mic,MonitorUp,Radio,Settings2,Video,VideoOff} from "lucide-react"

export function LiveStudio(){
 const videoRef=useRef<HTMLVideoElement>(null), streamRef=useRef<MediaStream|null>(null)
 const [camera,setCamera]=useState(false),[mic,setMic]=useState(true),[screen,setScreen]=useState(false),[status,setStatus]=useState<"ready"|"previewing"|"live">("ready")
 useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop())},[])
 async function toggleCamera(){
  if(camera){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setCamera(false);setStatus("ready");return}
  try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});streamRef.current=s;if(videoRef.current){videoRef.current.srcObject=s;await videoRef.current.play()}setCamera(true);setStatus("previewing")}catch{setCamera(false)}
 }
 async function shareScreen(){
  try{const s=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});if(videoRef.current){videoRef.current.srcObject=s;await videoRef.current.play()}setScreen(true);setStatus("previewing");s.getVideoTracks()[0].addEventListener("ended",()=>{setScreen(false);if(camera&&streamRef.current&&videoRef.current)videoRef.current.srcObject=streamRef.current})}catch{}
 }
 return <div className="space-y-5">
  <div className="rounded-2xl border border-border bg-secondary/30 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-brand-red">WIGOD Live Studio</p><h2 className="mt-1 font-serif text-xl font-bold">Your broadcast workspace</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Prepare your camera, microphone, screen and audience settings before starting a WIGOD Live session.</p></div><span className="rounded-full border border-border bg-background px-3 py-1.5 text-[11px] font-semibold">{status==="live"?"● Live":"● "+status}</span></div></div>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.5fr)]">
   <section className="space-y-4"><div className="relative aspect-video overflow-hidden rounded-2xl bg-black"><video ref={videoRef} muted playsInline className="size-full object-cover"/>{!camera&&!screen?<div className="absolute inset-0 flex flex-col items-center justify-center text-center text-white"><Video className="size-10 opacity-70"/><p className="mt-2 text-sm font-semibold">WIGOD Live preview</p><p className="mt-1 text-xs text-white/60">Turn on your camera or share your screen.</p></div>:null}<div className="absolute bottom-3 left-3 rounded-md bg-black/70 px-3 py-1.5 text-[10px] font-black tracking-widest text-white">WIGOD • PEOPLE. PLACES. PERSPECTIVES.</div></div>
    <div className="flex flex-wrap gap-2"><button onClick={toggleCamera} className="inline-flex items-center gap-2 rounded-xl bg-brand-green px-4 py-2.5 text-xs font-bold text-white">{camera?<VideoOff className="size-4"/>:<Camera className="size-4"/>}{camera?"Camera off":"Camera"}</button><button onClick={()=>setMic(v=>!v)} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 text-xs font-bold"><Mic className="size-4"/>{mic?"Mic on":"Mic muted"}</button><button onClick={shareScreen} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 text-xs font-bold"><MonitorUp className="size-4"/>Share screen</button></div>
    <div className="rounded-2xl border border-border p-4"><div className="flex items-center gap-2"><Radio className="size-4 text-brand-red"/><div><h3 className="text-sm font-bold">WIGOD Live</h3><p className="text-xs text-muted-foreground">Native WIGOD destination</p></div></div><p className="mt-3 text-xs leading-5 text-muted-foreground">Your broadcast is designed to live on WIGOD first. YouTube can remain an optional publishing connection; Facebook and TikTok are not required destinations.</p><button onClick={()=>setStatus("live")} disabled={!camera&&!screen} className="mt-4 w-full rounded-xl bg-brand-red px-4 py-3 text-sm font-bold text-white disabled:opacity-40">Start WIGOD Live</button><p className="mt-2 text-[10px] text-muted-foreground">The studio preview is functional. A production WebRTC/media server is still required to carry the live stream to viewers.</p></div>
   </section>
   <aside className="space-y-4"><div className="rounded-2xl border border-border p-4"><div className="flex items-center gap-2"><Settings2 className="size-4"/><h3 className="text-sm font-bold">Broadcast settings</h3></div><label className="mt-4 block text-xs font-semibold">Title</label><input defaultValue="WIGOD Live" className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm"/><label className="mt-3 block text-xs font-semibold">Description</label><textarea defaultValue="People. Places. Perspectives." className="mt-1 min-h-24 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm"/><label className="mt-3 block text-xs font-semibold">Visibility</label><select className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm"><option>Public</option><option>Unlisted</option><option>Private</option></select></div>
   <div className="rounded-2xl border border-border p-4"><h3 className="text-sm font-bold">Audience</h3><div className="mt-3 flex items-center justify-between rounded-xl border border-border px-3 py-3 text-xs"><span>Live comments</span><input type="checkbox" defaultChecked/></div><div className="mt-2 flex items-center justify-between rounded-xl border border-border px-3 py-3 text-xs"><span>Allow reactions</span><input type="checkbox" defaultChecked/></div></div>
   <div className="rounded-2xl border border-border bg-secondary/30 p-4"><p className="text-xs font-bold">Publishing</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">WIGOD is the primary destination. YouTube may be connected separately. No Facebook or TikTok destination is built into the WIGOD Live workflow.</p></div></aside>
  </div>
 </div>
}