services:
  wigod-broadcast-relay:
    image: bluenviron/mediamtx:1-ffmpeg
    restart: unless-stopped
    network_mode: host
    environment:
      YOUTUBE_RTMPS_URL: ${YOUTUBE_RTMPS_URL}
      MTX_WEBRTCADDITIONALHOSTS: ${WIGOD_BROADCAST_HOST}
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    command: ["/mediamtx", "/mediamtx.yml"]
